steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Docker Image'
  args:
  - 'build'
  - '-t'
  - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/h2s-artifact-repo/h2s-fastapi-app:${COMMIT_SHA}'
  - '.'

# Step 2: Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Docker Image'
  args:
  - 'push'
  - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/h2s-artifact-repo/h2s-fastapi-app:${COMMIT_SHA}'

# Step 3: Deploy the image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args:
  - 'run'
  - 'deploy'
  - 'cloud-build-service-accountt'
  - '--image'
  - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/h2s-artifact-repo/h2s-fastapi-app:${COMMIT_SHA}'
  - '--region'
  - 'europe-west1'
  - '--allow-unauthenticated'
  - '--service-account'
  - 'cloud-build-service-accountt@erudite-realm-472100-k9.iam.gserviceaccount.com'

images:
- 'europe-west1-docker.pkg.dev/${PROJECT_ID}/h2s-artifact-repo/h2s-fastapi-app:${COMMIT_SHA}'

# --- ADD THIS OPTIONS BLOCK ---
options:
  logging: GCS_ONLY # This tells Cloud Build to store logs in GCS
  logsBucket: 'gs://h2s-build-logs' # Specify your desired logs bucket here
